name: Build AIP and sign using Azure Trusted Sign

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    name: Build AIP and sign using Azure Trusted Sign    
    steps:   
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet 
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore Nuget packages
        run: nuget restore WinFormsApp.sln
      
      - name: Build Solution
        run: msbuild WinFormsApp.sln /t:WinFormsApp1 /p:Configuration="Release"

      - name: Build Package from AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: WinFormsApp.aip
          aip-build-name: DefaultBuild
          aip-package-name: WinFormsApp.msi
          aip-output-dir: ${{ github.workspace }}

      - name: Archive production artifacts (generated with advanced installer)
        uses: actions/upload-artifact@v2
        with:
          name: WinFormsApp
          path: WinFormsApp.msi
